services:

  mysql:
    image: mysql:8.0
    container_name: youthcamp-mysql
    restart: unless-stopped

    environment:
      MYSQL_DATABASE: mydb
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: youthcamp
      MYSQL_PASSWORD: youthcamp

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-proot"
        ]

      interval: 10s
      timeout: 5s
      retries: 10


  youthcamp-api:
    build: .

    container_name: youthcamp-api

    restart: unless-stopped

    depends_on:
      mysql:
        condition: service_healthy

    ports:
      - "8085:8085"

    environment:
      SPRING_PROFILES_ACTIVE: prod

      DATABASE_URL: jdbc:mysql://mysql:3306/mydb?serverTimezone=Asia/Kolkata

      DATABASE_USERNAME: youthcamp

      DATABASE_PASSWORD: youthcamp

      JWT_SECRET: youthcamp-production-secret-key-change-this

volumes:

  mysql_data: